CREATE TABLE STATISTIQUE (
IDENT_FILM 			INTEGER(5) NOT NULL,
DUREE 				INTEGER(4),
NB_ENTREE_FRANCE 	INTEGER(9),
RECETTE_USA 		INTEGER (9),
RECETTE_MONDE 		INTEGER(12),
BUDGET 				DECIMAL(3,2)
);

CREATE TABLE FILM(
IDENT_FILM 			INTEGER(5) NOT NULL,
TITRE 				VARCHAR(20),
GENRE1 				VARCHAR(20),
GENRE2 				VARCHAR(20),
DATE_SORTIE 		DATE,
PAYS 				TINYINT(2),
IDENT_REALISATEUR 	TINYINT(2),
DISTRIBUTEUR 		VARCHAR(20),
RESUME 				VARCHAR(100)
);

CREATE TABLE ACTEUR(
IDENT_ACTEUR 	INTEGER(5) NOT NULL,
NOM 			VARCHAR(20),
PRENOM 			VARCHAR(20),
DATE_NAISSANCE  DATE,
NB_FILM 		TINYINT(3),
NATIONALITE 	TINYINT(2)
);

CREATE TABLE REALISATEUR(
IDENT_REALISATEUR 	TINYINT(2),
NOM 				VARCHAR(20),	
PRENOM 				VARCHAR(20),
DATE_NAISSANCE 		DATE,
NB_FILM_ECRIT 		TINYINT(3),
NB_FILM_PRODUIT 	TINYINT(3),
NATIONALITE 		TINYINT(2)
);

CREATE TABLE CASTING(
IDENT_FILM 			INTEGER(5) NOT NULL,
IDENT_ACTEUR  		INTEGER(5) NOT NULL, 
ROLE 				VARCHAR(20),
NB_JOUR_TOURNAGE 	INTEGER(4)
);

CREATE TABLE PAYS(
IDENT_PAYS 			TINYINT(2),
LIBELLE 			VARCHAR(20)
);

ALTER TABLE FILM
MODIFY TITRE VARCHAR(40); 